[global]
type = global
user_agent = FrontdeskQ-Asterisk-Local

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[1001]
type = endpoint
transport = transport-udp
context = local-softphones
disallow = all
allow = ulaw,alaw
auth = 1001-auth
aors = 1001-aor
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes

[1001-auth]
type = auth
auth_type = userpass
username = 1001
password = frontdesk1001

[1001-aor]
type = aor
max_contacts = 1
remove_existing = yes

[1002]
type = endpoint
transport = transport-udp
context = local-softphones
disallow = all
allow = ulaw,alaw
auth = 1002-auth
aors = 1002-aor
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes

[1002-auth]
type = auth
auth_type = userpass
username = 1002
password = frontdesk1002

[1002-aor]
type = aor
max_contacts = 1
remove_existing = yes
